import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-doc-templates',
  templateUrl: './doc-templates.component.html',
  styleUrls: ['./doc-templates.component.scss']
})
export class DocTemplatesComponent implements OnInit {
  data: any;
  date: Date;

  constructor() { }

  ngOnInit(): void {
    this.date = new Date();
    this.data = [ 
      {
        title: "Inspection",
        templates : [
          { name : "IN Policies and Procedures" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "IN Consultation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "IN Vital Documents" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "IN Clients Responsibilities" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "IN Open Agreement" , access: "Published", status: "Not Published", lastUpdate: this.date },
          { name : "IN Capped Agreement" , access: "Published", status: "Not Published", lastUpdate: this.date },
          { name : "IN Payment Instructions" , access: "Published", status: "Not Published", lastUpdate: this.date },
          { name : "IN Client Binder Preparation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "IN Client Cover Page" , access: "", status: "Not Published", lastUpdate: this.date },
          { name : "IN Status Progress" , access: "", status: "Published", lastUpdate: this.date },
          { name : "IN Collection 1" , access: "", status: "Published", lastUpdate: this.date },
          { name : "IN Collection 2" , access: "", status: "Published", lastUpdate: this.date },
          { name : "IN Collection 3" , access: "", status: "Published", lastUpdate: this.date },
          { name : "IN Authorization" , access: "", status: "Published", lastUpdate: this.date },
          { name : "IN Lender and Client Benefit Analysis" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "IN Budget Template" , access: "", status: "Published", lastUpdate: this.date },
          { name : "IN Legal Binder" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "IN Regulator Binder" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "IN Fax Form" , access: "", status: "Published", lastUpdate: this.date },
          { name : "IN Letter of Explanation" , access: "", status: "Published", lastUpdate: this.date },
          { name : "IN Regulator Cover" , access: "", status: "Not Published", lastUpdate: this.date },
        ]
      },
      {
        title: "Real Estate Seller",
        templates : [
          { name : "RES Tax Star" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Mls Copy" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Exclusive Right To Sell" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES C Status" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES P Status" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES S Status" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Listing Agreement" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES MLS Change Order" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Duties Owed" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Supplemental Do" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Consent To Act By Owner" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Comps Signed By Owner" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Net Sheet Signed By Owner" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Broker Compensation Notice" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Broker Compensation Invoice" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Residential Disclosure Guide" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Copy Emd Or Receipt From Title" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Title PreLim Escrow" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Signed Commission Order" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES PreLim Acceptance" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Buyer Request For Repairs " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Home Inspection" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES SRPD By Owner" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Construction Defect Disclosureÿ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES SRPD By Buyer" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES CIC Addendum Resale Fees " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Hoa Certificate Of Resale Signed By Buyerÿ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Disclosures " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Authentisign/Electronic Signatureÿ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Beltway 2pg" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Fraud Wire" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Mold" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Pest" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Mechanical Lock Box" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Lead Based Paint 1978" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Did You Know You Are Buying An Reo" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Lender Short Sale Approval Add" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Short Sale Addendum For Listing" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Condo Conversionÿ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Home Warrantyÿ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Walk Throughÿ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Closing Packageÿ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES RPA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Counter Offer 1 " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Addendums " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Did You Know " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Hoa Accept" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES CMA " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Receipt For Your Protection " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES S Do " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES C To A " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Comps For Buyer " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Broker Comp Notice And Invoice " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES Residential Disclosure Guide " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "RES " , access: "Global", status: "Published", lastUpdate: this.date },
        ]
      },
      {
        title: "Loans",
        templates : [
          { name : "LN Policies and Procedures" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Auth to Pull Credit" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Intake Questionnaire" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Asset and Expense Questionnaire" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Creditor Schedule" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN CR Eval #1" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Estimate DS Schedule" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Budget Template" , access: "", status: "Published", lastUpdate: this.date },
          { name : "LN Consultation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Dodd Frank" , access: "", status: "Published", lastUpdate: this.date },
          { name : "LN Vital Documents" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Borrower Financials" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Non-Borrower Financials" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN RESPA Disclosure" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Clients Responsibilities" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Open Agreement" , access: "Published", status: "Not Published", lastUpdate: this.date },
          { name : "LN Capped Agreement" , access: "Published", status: "Not Published", lastUpdate: this.date },
          { name : "LN Authorization" , access: "", status: "Published", lastUpdate: this.date },
          { name : "LN POA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN POA Notarized" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN BK POA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN BK POA Notarized" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Financial Ledger" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN 4506-T" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN 4506-T EZ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Payment Instructions" , access: "Published", status: "Not Published", lastUpdate: this.date },
          { name : "LN Client Binder Preparation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Client Cover Page" , access: "", status: "Not Published", lastUpdate: this.date },
          { name : "LN Status Progress" , access: "", status: "Published", lastUpdate: this.date },
          { name : "LN Request Information" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Collection 1" , access: "", status: "Published", lastUpdate: this.date },
          { name : "LN Collection 2" , access: "", status: "Published", lastUpdate: this.date },
          { name : "LN Collection 3" , access: "", status: "Published", lastUpdate: this.date },
          { name : "LN Lender and Client Benefit Analysis" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Legal Binder" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Regulator Binder" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LN Fax Form" , access: "", status: "Published", lastUpdate: this.date },
          { name : "LN Letter of Explanation" , access: "", status: "Published", lastUpdate: this.date },
          { name : "LN Regulator Cover" , access: "", status: "Not Published", lastUpdate: this.date },
        ]
      },
      {       
        title: "Debt Settlement",
        templates : [
          { name : "DS Policies and Procedures" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Vital Documents List" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Collector Calls" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Client Responsibilities" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Auth to Pull Credit" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Consultation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Financial Hardship Memorandum" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Creditor Schedule" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS CR Eval #1" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Estimate DS Schedule" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Agreement" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS POA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS POA Notarized" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS BK POA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS BK POA Notarized" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Financial Ledger" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS 4506-T" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS 4506-T EZ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Request Information" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Request Verification" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Dispute Debt" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Contact Instructions" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Lawyer Contact" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Letter of Explanation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Status Progress" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Settlement Offer" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Settlement Schedule" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Offer Evaluation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Collection 1" , access: "", status: "Published", lastUpdate: this.date },
          { name : "DS Collection 2" , access: "", status: "Published", lastUpdate: this.date },
          { name : "DS Collection 3" , access: "", status: "Published", lastUpdate: this.date },
          { name : "DS CR Evaluation #2" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "DS Sales Brochure" , access: "Global", status: "Published", lastUpdate: this.date },
        ]
      },
      {
        title: "Credit Management",
        templates : [
          { name : "CR Policies and Procedures" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Consultation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Vital Documents List" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Collector Calls" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Client Responsibilities" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Auth to Pull Credit" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Financial Hardship Memorandum" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR CR Eval #1" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Agreement" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR POA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR POA Notarized" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR BK POA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR BK POA Notarized" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Financial Ledger" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR 4506-T" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR 4506-T EZ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Request Information" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Request Verification" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Dispute Debt" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Contact Instructions" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Lawyer Contact" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Letter of Explanation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Fax Cover" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR EQ Dispute" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR EX Dispute" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR TR Dispute" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Status Progress" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Collection 1" , access: "", status: "Published", lastUpdate: this.date },
          { name : "CR Collection 2" , access: "", status: "Published", lastUpdate: this.date },
          { name : "CR Collection 3" , access: "", status: "Published", lastUpdate: this.date },
          { name : "CR CR Evaluation #2" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Sales Brochure" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Credit Report Authorization for Chase" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Chase Financial Forms" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR NonBWR Occupy and Credit Number" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR WF Hardship Affidavit" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR WF Homeowner Financial Assistance Form" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR First Mortgage Corporation Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR SPS Financial Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR BB&T Mortgage Loss Mitigation Assistance Request Form" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Chase Monthly Expense Worksheet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR BOA Monthly Expenses" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR PNC Borrower Hardship Certification" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Washington Federal Borrower's Questionnaire" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Washington Federal MRC Application" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "CR Citi Financial Packet" , access: "Global", status: "Published", lastUpdate: this.date },
        ]
      },
      { 
        title: "Loan Modification",
        templates : [
          { name : "LM Procedures " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Vital docs" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Asset and Expense Questionnaire" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Loss Mitigation Intake Questionnaire" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Agreement" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM POA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM POA Notarized" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM BK POA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM BK POA Notarized" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM 4506-T" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM 4506-T EZ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Dodd Frank" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Financial Ledger" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Notification Emails to Clients" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Fax Cover" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM FHM" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM 7 Page RMA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Chase 9 Page RMA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM IndyMac RMA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM RMA-Interactive" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Chase 14 Page RMA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM HAFA-RMA 10 Page" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Ocwen 19 Page Financial Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Ocwen 21 Page Financial Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Form 710" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Fillable Form 710" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Borrower Financial Statement" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM FHA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Credit Report Authorization for Chase" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Chase Financials" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM NonBWR Occupy and Credit Number" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM WF Hardship Affidavit" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM WF Homeowner Financial Assistance Form" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM First Mortgage Corporation Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM SPS Financial Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM BB&T Mortgage Loss Mitigation Assistance Request Form" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Chase Monthly Expense Worksheet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM BOA Monthly Expenses" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Letter of Explanation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM PNC Borrower Hardship Certification" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Washington Federal Borrower's Questionnaire" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Washington Federal MRC Application" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Citi Financial Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Life of Loan Evaluation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Summary of Services" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Loss Mitigation Timeline" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Sales Receipt Template" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM FMP Violation List" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM FED Violation List" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM NRS Violation List" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "LM Completion of Trial" , access: "Global", status: "Published", lastUpdate: this.date },
        ]
      },
      {
        title: "Short Sale",
        templates : [
          { name : "SS Procedures " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Vital docs" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Asset and Expense Questionnaire" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Loss Mitigation Intake Questionnaire" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Agreement" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS POA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS POA Notarized" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS BK POA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS BK POA Notarized" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS 4506-T" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS 4506-T EZ" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Listing Agreement" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Duties Owed by a Nevada Real Estate Licensee" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Seller’s Real Property Disclosure Form" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Residential Disclosure Guide" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Consent to Act" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Lead Based Paint Disclosure" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Mold Notice and Waiver" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Resale Package Receipt" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Property listed on MLS" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Listing Agreement and Power of Attorney submitted to Lender" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Confirmation of Listing to Broker(sent)" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Confirmation of Listing to Broker(received)" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Dodd Frank" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Financial Ledger" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Notification Emails to Clients" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Fax Cover" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS FHM" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS 7 Page RMA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Chase 9 Page RMA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS IndyMac RMA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS RMA-Interactive" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Chase 14 Page RMA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS HAFA-RMA 10 Page" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Ocwen 19 Page Financial Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Ocwen 21 Page Financial Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Form 710" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Fillable Form 710" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Borrower Financial Statement" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS FHA" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Credit Report Authorization for Chase" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Chase Financials" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS NonBWR Occupy and Credit Number" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS WF Hardship Affidavit" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS WF Homeowner Financial Assistance Form" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS First Mortgage Corporation Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS SPS Financial Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS BB&T Mortgage Loss Mitigation Assistance Request Form" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Chase Monthly Expense Worksheet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS BOA Monthly Expenses" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Letter of Explanation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS PNC Borrower Hardship Certification" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Washington Federal Borrower's Questionnaire" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Washington Federal MRC Application" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Citi Financial Packet" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Life of Loan Evaluation" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Summary of Services" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Loss Mitigation Timeline" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Sales Receipt Template" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS FMP Violation List" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS FED Violation List" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS NRS Violation List" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "SS Completion of Trial" , access: "Global", status: "Published", lastUpdate: this.date },
        ]
      },
      {
        title: "Foreclosure Mediation",
        templates : [
          { name : "FM Procedures " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Collector Calls " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Vital Documents " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Binder Preparation " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Consultation " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Foreclosure Intake " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Intake Household Financials " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Agreement " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Capped Agreement " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Client Responsibilities " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Status Progress " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Financial Ledger " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Power of Attorney #1 " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Power of Attorney #2 " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Authorization " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Request for Information " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Budget Template " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Financial Hardship Memorandum " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Fax Form " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Qualified Written Request (QWR) " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM QWR Violation Letter " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Lender and Client Benefit Analysis " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Life of Loan Evaluation " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM 4506-T " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Dodd Frank Certification " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Mediation Agreement " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Mediation Election " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Mediation Financial Statement " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Mediation Housing Affordability " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Mediation Proposal for Resolution " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Mediation Cover Page " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Mediation Offer Checklist/Life of Loan " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Mediation Rules Checklist " , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "FM Mediation Continuance " , access: "Global", status: "Published", lastUpdate: this.date },
        ]
      },
      {
        title: "Independent Foreclosure Mediation",
        templates : [
          { name : "IFR Foreclosure Independent Review" , access: "Global", status: "Published", lastUpdate: this.date },
          { name : "M Testimony-Occ-Cohen" , access: "", status: "Not Published", lastUpdate: this.date },
        ]
      }
    ]
  }

}
